baseURL = "https://hyunh.github.io/"
languageCode = "en-us"
title = "HyunH"
theme = "hugo-book"

[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
  BookTheme = "auto"
  BookToC = false

[languages.en]
  languageName = 'English'
  weight = 1

[languages.ko]
  languageName = 'Korean'
  weight = 2

[[menu.icon]]
  name = "github"
  url = "https://github.com/hyunh"
  weight = 1

[[menu.icon]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/hyunhae-lee-143a16123/"
  weight = 2
